CRITICAL - 2022-11-11 00:52:12 --> Invalid file: signup.php
in SYSTEMPATH\Exceptions\FrameworkException.php on line 33.
 1 SYSTEMPATH\View\View.php(201): CodeIgniter\Exceptions\FrameworkException::forInvalidFile('signup.php')
 2 SYSTEMPATH\Common.php(1134): CodeIgniter\View\View->render('signup', [], true)
 3 APPPATH\Controllers\signup.php(13): view('signup', [])
 4 SYSTEMPATH\CodeIgniter.php(927): App\Controllers\signup->index()
 5 SYSTEMPATH\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\signup))
 6 SYSTEMPATH\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2022-11-11 00:52:36 --> Invalid file: signup.php
in SYSTEMPATH\Exceptions\FrameworkException.php on line 33.
 1 SYSTEMPATH\View\View.php(201): CodeIgniter\Exceptions\FrameworkException::forInvalidFile('signup.php')
 2 SYSTEMPATH\Common.php(1134): CodeIgniter\View\View->render('signup', [], true)
 3 APPPATH\Controllers\signup.php(13): view('signup', [])
 4 SYSTEMPATH\CodeIgniter.php(927): App\Controllers\signup->index()
 5 SYSTEMPATH\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\signup))
 6 SYSTEMPATH\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2022-11-11 00:53:57 --> Invalid file: signup.php
in SYSTEMPATH\Exceptions\FrameworkException.php on line 33.
 1 SYSTEMPATH\View\View.php(201): CodeIgniter\Exceptions\FrameworkException::forInvalidFile('signup.php')
 2 SYSTEMPATH\Common.php(1134): CodeIgniter\View\View->render('signup', [], true)
 3 APPPATH\Controllers\signup.php(13): view('signup')
 4 SYSTEMPATH\CodeIgniter.php(927): App\Controllers\signup->index()
 5 SYSTEMPATH\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\signup))
 6 SYSTEMPATH\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2022-11-11 00:53:58 --> Invalid file: signup.php
in SYSTEMPATH\Exceptions\FrameworkException.php on line 33.
 1 SYSTEMPATH\View\View.php(201): CodeIgniter\Exceptions\FrameworkException::forInvalidFile('signup.php')
 2 SYSTEMPATH\Common.php(1134): CodeIgniter\View\View->render('signup', [], true)
 3 APPPATH\Controllers\signup.php(13): view('signup')
 4 SYSTEMPATH\CodeIgniter.php(927): App\Controllers\signup->index()
 5 SYSTEMPATH\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\signup))
 6 SYSTEMPATH\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2022-11-11 00:54:09 --> Invalid file: signup.php
in SYSTEMPATH\Exceptions\FrameworkException.php on line 33.
 1 SYSTEMPATH\View\View.php(201): CodeIgniter\Exceptions\FrameworkException::forInvalidFile('signup.php')
 2 SYSTEMPATH\Common.php(1134): CodeIgniter\View\View->render('signup', [], true)
 3 APPPATH\Controllers\signup.php(13): view('signup')
 4 SYSTEMPATH\CodeIgniter.php(927): App\Controllers\signup->index()
 5 SYSTEMPATH\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\signup))
 6 SYSTEMPATH\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
ERROR - 2022-11-11 00:54:52 --> mysqli_sql_exception: Table 'zavme.users' doesn't exist in C:\xampp\htdocs\CI\system\Database\MySQLi\Connection.php:292
Stack trace:
#0 C:\xampp\htdocs\CI\system\Database\MySQLi\Connection.php(292): mysqli->query('SELECT 1\nFROM `...', 0)
#1 C:\xampp\htdocs\CI\system\Database\BaseConnection.php(666): CodeIgniter\Database\MySQLi\Connection->execute('SELECT 1\nFROM `...')
#2 C:\xampp\htdocs\CI\system\Database\BaseConnection.php(593): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT 1\nFROM `...')
#3 C:\xampp\htdocs\CI\system\Database\BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query('SELECT 1\nFROM `...', Array, false)
#4 C:\xampp\htdocs\CI\system\Validation\Rules.php(142): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp\htdocs\CI\system\Validation\Validation.php(315): CodeIgniter\Validation\Rules->is_unique('admin123@gmail....', 'email', Array, NULL, 'email')
#6 C:\xampp\htdocs\CI\system\Validation\Validation.php(175): CodeIgniter\Validation\Validation->processRules('email', 'email', 'admin123@gmail....', Array, Array)
#7 C:\xampp\htdocs\CI\system\Controller.php(140): CodeIgniter\Validation\Validation->run()
#8 C:\xampp\htdocs\CI\app\Controllers\signup.php(26): CodeIgniter\Controller->validate(Array)
#9 C:\xampp\htdocs\CI\system\CodeIgniter.php(927): App\Controllers\signup->store()
#10 C:\xampp\htdocs\CI\system\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\signup))
#11 C:\xampp\htdocs\CI\system\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 C:\xampp\htdocs\CI\public\index.php(67): CodeIgniter\CodeIgniter->run()
#13 {main}
CRITICAL - 2022-11-11 00:54:52 --> Call to a member function getRow() on bool
in SYSTEMPATH\Validation\Rules.php on line 142.
 1 SYSTEMPATH\Validation\Validation.php(315): CodeIgniter\Validation\Rules->is_unique('admin123@gmail.com', 'email', [...], null, 'email')
 2 SYSTEMPATH\Validation\Validation.php(175): CodeIgniter\Validation\Validation->processRules('email', 'email', 'admin123@gmail.com', [...], [...])
 3 SYSTEMPATH\Controller.php(140): CodeIgniter\Validation\Validation->run()
 4 APPPATH\Controllers\signup.php(26): CodeIgniter\Controller->validate([...])
 5 SYSTEMPATH\CodeIgniter.php(927): App\Controllers\signup->store()
 6 SYSTEMPATH\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\signup))
 7 SYSTEMPATH\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
ERROR - 2022-11-11 00:57:11 --> mysqli_sql_exception: Table 'zavme.users' doesn't exist in C:\xampp\htdocs\CI\system\Database\MySQLi\Connection.php:292
Stack trace:
#0 C:\xampp\htdocs\CI\system\Database\MySQLi\Connection.php(292): mysqli->query('SELECT 1\nFROM `...', 0)
#1 C:\xampp\htdocs\CI\system\Database\BaseConnection.php(666): CodeIgniter\Database\MySQLi\Connection->execute('SELECT 1\nFROM `...')
#2 C:\xampp\htdocs\CI\system\Database\BaseConnection.php(593): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT 1\nFROM `...')
#3 C:\xampp\htdocs\CI\system\Database\BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query('SELECT 1\nFROM `...', Array, false)
#4 C:\xampp\htdocs\CI\system\Validation\Rules.php(142): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp\htdocs\CI\system\Validation\Validation.php(315): CodeIgniter\Validation\Rules->is_unique('admin123@gmail....', 'email', Array, NULL, 'email')
#6 C:\xampp\htdocs\CI\system\Validation\Validation.php(175): CodeIgniter\Validation\Validation->processRules('email', 'email', 'admin123@gmail....', Array, Array)
#7 C:\xampp\htdocs\CI\system\Controller.php(140): CodeIgniter\Validation\Validation->run()
#8 C:\xampp\htdocs\CI\app\Controllers\signup.php(26): CodeIgniter\Controller->validate(Array)
#9 C:\xampp\htdocs\CI\system\CodeIgniter.php(927): App\Controllers\signup->store()
#10 C:\xampp\htdocs\CI\system\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\signup))
#11 C:\xampp\htdocs\CI\system\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 C:\xampp\htdocs\CI\public\index.php(67): CodeIgniter\CodeIgniter->run()
#13 {main}
CRITICAL - 2022-11-11 00:57:11 --> Call to a member function getRow() on bool
in SYSTEMPATH\Validation\Rules.php on line 142.
 1 SYSTEMPATH\Validation\Validation.php(315): CodeIgniter\Validation\Rules->is_unique('admin123@gmail.com', 'email', [...], null, 'email')
 2 SYSTEMPATH\Validation\Validation.php(175): CodeIgniter\Validation\Validation->processRules('email', 'email', 'admin123@gmail.com', [...], [...])
 3 SYSTEMPATH\Controller.php(140): CodeIgniter\Validation\Validation->run()
 4 APPPATH\Controllers\signup.php(26): CodeIgniter\Controller->validate([...])
 5 SYSTEMPATH\CodeIgniter.php(927): App\Controllers\signup->store()
 6 SYSTEMPATH\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\signup))
 7 SYSTEMPATH\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
ERROR - 2022-11-11 00:57:13 --> mysqli_sql_exception: Table 'zavme.users' doesn't exist in C:\xampp\htdocs\CI\system\Database\MySQLi\Connection.php:292
Stack trace:
#0 C:\xampp\htdocs\CI\system\Database\MySQLi\Connection.php(292): mysqli->query('SELECT 1\nFROM `...', 0)
#1 C:\xampp\htdocs\CI\system\Database\BaseConnection.php(666): CodeIgniter\Database\MySQLi\Connection->execute('SELECT 1\nFROM `...')
#2 C:\xampp\htdocs\CI\system\Database\BaseConnection.php(593): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT 1\nFROM `...')
#3 C:\xampp\htdocs\CI\system\Database\BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query('SELECT 1\nFROM `...', Array, false)
#4 C:\xampp\htdocs\CI\system\Validation\Rules.php(142): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp\htdocs\CI\system\Validation\Validation.php(315): CodeIgniter\Validation\Rules->is_unique('admin123@gmail....', 'email', Array, NULL, 'email')
#6 C:\xampp\htdocs\CI\system\Validation\Validation.php(175): CodeIgniter\Validation\Validation->processRules('email', 'email', 'admin123@gmail....', Array, Array)
#7 C:\xampp\htdocs\CI\system\Controller.php(140): CodeIgniter\Validation\Validation->run()
#8 C:\xampp\htdocs\CI\app\Controllers\signup.php(26): CodeIgniter\Controller->validate(Array)
#9 C:\xampp\htdocs\CI\system\CodeIgniter.php(927): App\Controllers\signup->store()
#10 C:\xampp\htdocs\CI\system\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\signup))
#11 C:\xampp\htdocs\CI\system\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 C:\xampp\htdocs\CI\public\index.php(67): CodeIgniter\CodeIgniter->run()
#13 {main}
CRITICAL - 2022-11-11 00:57:13 --> Call to a member function getRow() on bool
in SYSTEMPATH\Validation\Rules.php on line 142.
 1 SYSTEMPATH\Validation\Validation.php(315): CodeIgniter\Validation\Rules->is_unique('admin123@gmail.com', 'email', [...], null, 'email')
 2 SYSTEMPATH\Validation\Validation.php(175): CodeIgniter\Validation\Validation->processRules('email', 'email', 'admin123@gmail.com', [...], [...])
 3 SYSTEMPATH\Controller.php(140): CodeIgniter\Validation\Validation->run()
 4 APPPATH\Controllers\signup.php(26): CodeIgniter\Controller->validate([...])
 5 SYSTEMPATH\CodeIgniter.php(927): App\Controllers\signup->store()
 6 SYSTEMPATH\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\signup))
 7 SYSTEMPATH\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
ERROR - 2022-11-11 00:58:00 --> mysqli_sql_exception: Table 'zavme.users' doesn't exist in C:\xampp\htdocs\CI\system\Database\MySQLi\Connection.php:292
Stack trace:
#0 C:\xampp\htdocs\CI\system\Database\MySQLi\Connection.php(292): mysqli->query('SELECT 1\nFROM `...', 0)
#1 C:\xampp\htdocs\CI\system\Database\BaseConnection.php(666): CodeIgniter\Database\MySQLi\Connection->execute('SELECT 1\nFROM `...')
#2 C:\xampp\htdocs\CI\system\Database\BaseConnection.php(593): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT 1\nFROM `...')
#3 C:\xampp\htdocs\CI\system\Database\BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query('SELECT 1\nFROM `...', Array, false)
#4 C:\xampp\htdocs\CI\system\Validation\Rules.php(142): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp\htdocs\CI\system\Validation\Validation.php(315): CodeIgniter\Validation\Rules->is_unique('admin123@gmail....', 'email', Array, NULL, 'email')
#6 C:\xampp\htdocs\CI\system\Validation\Validation.php(175): CodeIgniter\Validation\Validation->processRules('email', 'email', 'admin123@gmail....', Array, Array)
#7 C:\xampp\htdocs\CI\system\Controller.php(140): CodeIgniter\Validation\Validation->run()
#8 C:\xampp\htdocs\CI\app\Controllers\signup.php(26): CodeIgniter\Controller->validate(Array)
#9 C:\xampp\htdocs\CI\system\CodeIgniter.php(927): App\Controllers\signup->store()
#10 C:\xampp\htdocs\CI\system\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\signup))
#11 C:\xampp\htdocs\CI\system\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 C:\xampp\htdocs\CI\public\index.php(67): CodeIgniter\CodeIgniter->run()
#13 {main}
CRITICAL - 2022-11-11 00:58:00 --> Call to a member function getRow() on bool
in SYSTEMPATH\Validation\Rules.php on line 142.
 1 SYSTEMPATH\Validation\Validation.php(315): CodeIgniter\Validation\Rules->is_unique('admin123@gmail.com', 'email', [...], null, 'email')
 2 SYSTEMPATH\Validation\Validation.php(175): CodeIgniter\Validation\Validation->processRules('email', 'email', 'admin123@gmail.com', [...], [...])
 3 SYSTEMPATH\Controller.php(140): CodeIgniter\Validation\Validation->run()
 4 APPPATH\Controllers\signup.php(26): CodeIgniter\Controller->validate([...])
 5 SYSTEMPATH\CodeIgniter.php(927): App\Controllers\signup->store()
 6 SYSTEMPATH\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\signup))
 7 SYSTEMPATH\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
ERROR - 2022-11-11 01:00:21 --> mysqli_sql_exception: Table 'zavme.users' doesn't exist in C:\xampp\htdocs\CI\system\Database\MySQLi\Connection.php:292
Stack trace:
#0 C:\xampp\htdocs\CI\system\Database\MySQLi\Connection.php(292): mysqli->query('SELECT 1\nFROM `...', 0)
#1 C:\xampp\htdocs\CI\system\Database\BaseConnection.php(666): CodeIgniter\Database\MySQLi\Connection->execute('SELECT 1\nFROM `...')
#2 C:\xampp\htdocs\CI\system\Database\BaseConnection.php(593): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT 1\nFROM `...')
#3 C:\xampp\htdocs\CI\system\Database\BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query('SELECT 1\nFROM `...', Array, false)
#4 C:\xampp\htdocs\CI\system\Validation\Rules.php(142): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp\htdocs\CI\system\Validation\Validation.php(315): CodeIgniter\Validation\Rules->is_unique('admin123@gmail....', 'email', Array, NULL, 'email')
#6 C:\xampp\htdocs\CI\system\Validation\Validation.php(175): CodeIgniter\Validation\Validation->processRules('email', 'email', 'admin123@gmail....', Array, Array)
#7 C:\xampp\htdocs\CI\system\Controller.php(140): CodeIgniter\Validation\Validation->run()
#8 C:\xampp\htdocs\CI\app\Controllers\signup.php(26): CodeIgniter\Controller->validate(Array)
#9 C:\xampp\htdocs\CI\system\CodeIgniter.php(927): App\Controllers\signup->store()
#10 C:\xampp\htdocs\CI\system\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\signup))
#11 C:\xampp\htdocs\CI\system\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 C:\xampp\htdocs\CI\public\index.php(67): CodeIgniter\CodeIgniter->run()
#13 {main}
CRITICAL - 2022-11-11 01:00:21 --> Call to a member function getRow() on bool
in SYSTEMPATH\Validation\Rules.php on line 142.
 1 SYSTEMPATH\Validation\Validation.php(315): CodeIgniter\Validation\Rules->is_unique('admin123@gmail.com', 'email', [...], null, 'email')
 2 SYSTEMPATH\Validation\Validation.php(175): CodeIgniter\Validation\Validation->processRules('email', 'email', 'admin123@gmail.com', [...], [...])
 3 SYSTEMPATH\Controller.php(140): CodeIgniter\Validation\Validation->run()
 4 APPPATH\Controllers\signup.php(26): CodeIgniter\Controller->validate([...])
 5 SYSTEMPATH\CodeIgniter.php(927): App\Controllers\signup->store()
 6 SYSTEMPATH\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\signup))
 7 SYSTEMPATH\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
ERROR - 2022-11-11 01:04:04 --> mysqli_sql_exception: Table 'zavme.users' doesn't exist in C:\xampp\htdocs\CI\system\Database\MySQLi\Connection.php:292
Stack trace:
#0 C:\xampp\htdocs\CI\system\Database\MySQLi\Connection.php(292): mysqli->query('SELECT 1\nFROM `...', 0)
#1 C:\xampp\htdocs\CI\system\Database\BaseConnection.php(666): CodeIgniter\Database\MySQLi\Connection->execute('SELECT 1\nFROM `...')
#2 C:\xampp\htdocs\CI\system\Database\BaseConnection.php(593): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT 1\nFROM `...')
#3 C:\xampp\htdocs\CI\system\Database\BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query('SELECT 1\nFROM `...', Array, false)
#4 C:\xampp\htdocs\CI\system\Validation\Rules.php(142): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp\htdocs\CI\system\Validation\Validation.php(315): CodeIgniter\Validation\Rules->is_unique('admin123@gmail....', 'email', Array, NULL, 'email')
#6 C:\xampp\htdocs\CI\system\Validation\Validation.php(175): CodeIgniter\Validation\Validation->processRules('email', 'email', 'admin123@gmail....', Array, Array)
#7 C:\xampp\htdocs\CI\system\Controller.php(140): CodeIgniter\Validation\Validation->run()
#8 C:\xampp\htdocs\CI\app\Controllers\signup.php(26): CodeIgniter\Controller->validate(Array)
#9 C:\xampp\htdocs\CI\system\CodeIgniter.php(927): App\Controllers\signup->store()
#10 C:\xampp\htdocs\CI\system\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\signup))
#11 C:\xampp\htdocs\CI\system\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 C:\xampp\htdocs\CI\public\index.php(67): CodeIgniter\CodeIgniter->run()
#13 {main}
CRITICAL - 2022-11-11 01:04:04 --> Call to a member function getRow() on bool
in SYSTEMPATH\Validation\Rules.php on line 142.
 1 SYSTEMPATH\Validation\Validation.php(315): CodeIgniter\Validation\Rules->is_unique('admin123@gmail.com', 'email', [...], null, 'email')
 2 SYSTEMPATH\Validation\Validation.php(175): CodeIgniter\Validation\Validation->processRules('email', 'email', 'admin123@gmail.com', [...], [...])
 3 SYSTEMPATH\Controller.php(140): CodeIgniter\Validation\Validation->run()
 4 APPPATH\Controllers\signup.php(26): CodeIgniter\Controller->validate([...])
 5 SYSTEMPATH\CodeIgniter.php(927): App\Controllers\signup->store()
 6 SYSTEMPATH\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\signup))
 7 SYSTEMPATH\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
ERROR - 2022-11-11 01:11:04 --> mysqli_sql_exception: Table 'zavme.users' doesn't exist in C:\xampp\htdocs\CI\system\Database\MySQLi\Connection.php:292
Stack trace:
#0 C:\xampp\htdocs\CI\system\Database\MySQLi\Connection.php(292): mysqli->query('SELECT 1\nFROM `...', 0)
#1 C:\xampp\htdocs\CI\system\Database\BaseConnection.php(666): CodeIgniter\Database\MySQLi\Connection->execute('SELECT 1\nFROM `...')
#2 C:\xampp\htdocs\CI\system\Database\BaseConnection.php(593): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT 1\nFROM `...')
#3 C:\xampp\htdocs\CI\system\Database\BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query('SELECT 1\nFROM `...', Array, false)
#4 C:\xampp\htdocs\CI\system\Validation\Rules.php(142): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp\htdocs\CI\system\Validation\Validation.php(315): CodeIgniter\Validation\Rules->is_unique('admin123@gmail....', 'email', Array, NULL, 'email')
#6 C:\xampp\htdocs\CI\system\Validation\Validation.php(175): CodeIgniter\Validation\Validation->processRules('email', 'email', 'admin123@gmail....', Array, Array)
#7 C:\xampp\htdocs\CI\system\Controller.php(140): CodeIgniter\Validation\Validation->run()
#8 C:\xampp\htdocs\CI\app\Controllers\signup.php(27): CodeIgniter\Controller->validate(Array)
#9 C:\xampp\htdocs\CI\system\CodeIgniter.php(927): App\Controllers\signup->store()
#10 C:\xampp\htdocs\CI\system\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\signup))
#11 C:\xampp\htdocs\CI\system\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 C:\xampp\htdocs\CI\public\index.php(67): CodeIgniter\CodeIgniter->run()
#13 {main}
CRITICAL - 2022-11-11 01:11:04 --> Call to a member function getRow() on bool
in SYSTEMPATH\Validation\Rules.php on line 142.
 1 SYSTEMPATH\Validation\Validation.php(315): CodeIgniter\Validation\Rules->is_unique('admin123@gmail.com', 'email', [...], null, 'email')
 2 SYSTEMPATH\Validation\Validation.php(175): CodeIgniter\Validation\Validation->processRules('email', 'email', 'admin123@gmail.com', [...], [...])
 3 SYSTEMPATH\Controller.php(140): CodeIgniter\Validation\Validation->run()
 4 APPPATH\Controllers\signup.php(27): CodeIgniter\Controller->validate([...])
 5 SYSTEMPATH\CodeIgniter.php(927): App\Controllers\signup->store()
 6 SYSTEMPATH\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\signup))
 7 SYSTEMPATH\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
ERROR - 2022-11-11 01:13:56 --> mysqli_sql_exception: Table 'zavme.users' doesn't exist in C:\xampp\htdocs\CI\system\Database\MySQLi\Connection.php:292
Stack trace:
#0 C:\xampp\htdocs\CI\system\Database\MySQLi\Connection.php(292): mysqli->query('SELECT 1\nFROM `...', 0)
#1 C:\xampp\htdocs\CI\system\Database\BaseConnection.php(666): CodeIgniter\Database\MySQLi\Connection->execute('SELECT 1\nFROM `...')
#2 C:\xampp\htdocs\CI\system\Database\BaseConnection.php(593): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT 1\nFROM `...')
#3 C:\xampp\htdocs\CI\system\Database\BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query('SELECT 1\nFROM `...', Array, false)
#4 C:\xampp\htdocs\CI\system\Validation\Rules.php(142): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp\htdocs\CI\system\Validation\Validation.php(315): CodeIgniter\Validation\Rules->is_unique('admin123@gmail....', 'email', Array, NULL, 'email')
#6 C:\xampp\htdocs\CI\system\Validation\Validation.php(175): CodeIgniter\Validation\Validation->processRules('email', 'email', 'admin123@gmail....', Array, Array)
#7 C:\xampp\htdocs\CI\system\Controller.php(140): CodeIgniter\Validation\Validation->run()
#8 C:\xampp\htdocs\CI\app\Controllers\signup.php(27): CodeIgniter\Controller->validate(Array)
#9 C:\xampp\htdocs\CI\system\CodeIgniter.php(927): App\Controllers\signup->store()
#10 C:\xampp\htdocs\CI\system\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\signup))
#11 C:\xampp\htdocs\CI\system\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 C:\xampp\htdocs\CI\public\index.php(67): CodeIgniter\CodeIgniter->run()
#13 {main}
CRITICAL - 2022-11-11 01:13:56 --> Call to a member function getRow() on bool
in SYSTEMPATH\Validation\Rules.php on line 142.
 1 SYSTEMPATH\Validation\Validation.php(315): CodeIgniter\Validation\Rules->is_unique('admin123@gmail.com', 'email', [...], null, 'email')
 2 SYSTEMPATH\Validation\Validation.php(175): CodeIgniter\Validation\Validation->processRules('email', 'email', 'admin123@gmail.com', [...], [...])
 3 SYSTEMPATH\Controller.php(140): CodeIgniter\Validation\Validation->run()
 4 APPPATH\Controllers\signup.php(27): CodeIgniter\Controller->validate([...])
 5 SYSTEMPATH\CodeIgniter.php(927): App\Controllers\signup->store()
 6 SYSTEMPATH\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\signup))
 7 SYSTEMPATH\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
ERROR - 2022-11-11 01:14:06 --> mysqli_sql_exception: Table 'zavme.users' doesn't exist in C:\xampp\htdocs\CI\system\Database\MySQLi\Connection.php:292
Stack trace:
#0 C:\xampp\htdocs\CI\system\Database\MySQLi\Connection.php(292): mysqli->query('SELECT 1\nFROM `...', 0)
#1 C:\xampp\htdocs\CI\system\Database\BaseConnection.php(666): CodeIgniter\Database\MySQLi\Connection->execute('SELECT 1\nFROM `...')
#2 C:\xampp\htdocs\CI\system\Database\BaseConnection.php(593): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT 1\nFROM `...')
#3 C:\xampp\htdocs\CI\system\Database\BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query('SELECT 1\nFROM `...', Array, false)
#4 C:\xampp\htdocs\CI\system\Validation\Rules.php(142): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp\htdocs\CI\system\Validation\Validation.php(315): CodeIgniter\Validation\Rules->is_unique('admin123@gmail....', 'email', Array, NULL, 'email')
#6 C:\xampp\htdocs\CI\system\Validation\Validation.php(175): CodeIgniter\Validation\Validation->processRules('email', 'email', 'admin123@gmail....', Array, Array)
#7 C:\xampp\htdocs\CI\system\Controller.php(140): CodeIgniter\Validation\Validation->run()
#8 C:\xampp\htdocs\CI\app\Controllers\signup.php(27): CodeIgniter\Controller->validate(Array)
#9 C:\xampp\htdocs\CI\system\CodeIgniter.php(927): App\Controllers\signup->store()
#10 C:\xampp\htdocs\CI\system\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\signup))
#11 C:\xampp\htdocs\CI\system\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 C:\xampp\htdocs\CI\public\index.php(67): CodeIgniter\CodeIgniter->run()
#13 {main}
CRITICAL - 2022-11-11 01:14:06 --> Call to a member function getRow() on bool
in SYSTEMPATH\Validation\Rules.php on line 142.
 1 SYSTEMPATH\Validation\Validation.php(315): CodeIgniter\Validation\Rules->is_unique('admin123@gmail.com', 'email', [...], null, 'email')
 2 SYSTEMPATH\Validation\Validation.php(175): CodeIgniter\Validation\Validation->processRules('email', 'email', 'admin123@gmail.com', [...], [...])
 3 SYSTEMPATH\Controller.php(140): CodeIgniter\Validation\Validation->run()
 4 APPPATH\Controllers\signup.php(27): CodeIgniter\Controller->validate([...])
 5 SYSTEMPATH\CodeIgniter.php(927): App\Controllers\signup->store()
 6 SYSTEMPATH\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\signup))
 7 SYSTEMPATH\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2022-11-11 01:21:59 --> syntax error, unexpected variable "$db", expecting "function" or "const"
in APPPATH\Models\UserModel.php on line 8.
 1 SYSTEMPATH\Autoloader\Autoloader.php(259): CodeIgniter\Autoloader\Autoloader->includeFile('APPPATH\\Models\\UserModel.php')
 2 SYSTEMPATH\Autoloader\Autoloader.php(237): CodeIgniter\Autoloader\Autoloader->loadInNamespace('App\\Models\\UserModel')
 3 APPPATH\Controllers\signup.php(27): CodeIgniter\Autoloader\Autoloader->loadClass('App\\Models\\UserModel')
 4 SYSTEMPATH\CodeIgniter.php(927): App\Controllers\signup->store()
 5 SYSTEMPATH\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\signup))
 6 SYSTEMPATH\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
ERROR - 2022-11-11 08:58:57 --> mysqli_sql_exception: Duplicate entry 'admin123@gmail.com' for key 'PRIMARY' in C:\xampp\htdocs\CI\system\Database\MySQLi\Connection.php:292
Stack trace:
#0 C:\xampp\htdocs\CI\system\Database\MySQLi\Connection.php(292): mysqli->query('INSERT INTO `lo...', 0)
#1 C:\xampp\htdocs\CI\system\Database\BaseConnection.php(666): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `lo...')
#2 C:\xampp\htdocs\CI\system\Database\BaseConnection.php(593): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `lo...')
#3 C:\xampp\htdocs\CI\system\Database\BaseBuilder.php(1916): CodeIgniter\Database\BaseConnection->query('INSERT INTO `lo...', Array, false)
#4 C:\xampp\htdocs\CI\system\Model.php(279): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\xampp\htdocs\CI\system\BaseModel.php(749): CodeIgniter\Model->doInsert(Array)
#6 C:\xampp\htdocs\CI\system\Model.php(667): CodeIgniter\BaseModel->insert(Array, false)
#7 C:\xampp\htdocs\CI\system\BaseModel.php(659): CodeIgniter\Model->insert(Array, false)
#8 C:\xampp\htdocs\CI\app\Controllers\signup.php(33): CodeIgniter\BaseModel->save(Array)
#9 C:\xampp\htdocs\CI\system\CodeIgniter.php(927): App\Controllers\signup->store()
#10 C:\xampp\htdocs\CI\system\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\signup))
#11 C:\xampp\htdocs\CI\system\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 C:\xampp\htdocs\CI\public\index.php(67): CodeIgniter\CodeIgniter->run()
#13 {main}
ERROR - 2022-11-11 09:23:54 --> mysqli_sql_exception: Table 'zavme.users' doesn't exist in C:\xampp\htdocs\CI\system\Database\MySQLi\Connection.php:292
Stack trace:
#0 C:\xampp\htdocs\CI\system\Database\MySQLi\Connection.php(292): mysqli->query('SELECT 1\nFROM `...', 0)
#1 C:\xampp\htdocs\CI\system\Database\BaseConnection.php(666): CodeIgniter\Database\MySQLi\Connection->execute('SELECT 1\nFROM `...')
#2 C:\xampp\htdocs\CI\system\Database\BaseConnection.php(593): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT 1\nFROM `...')
#3 C:\xampp\htdocs\CI\system\Database\BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query('SELECT 1\nFROM `...', Array, false)
#4 C:\xampp\htdocs\CI\system\Validation\Rules.php(142): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp\htdocs\CI\system\Validation\Validation.php(315): CodeIgniter\Validation\Rules->is_unique('admin123@gmail....', 'email', Array, NULL, 'email')
#6 C:\xampp\htdocs\CI\system\Validation\Validation.php(175): CodeIgniter\Validation\Validation->processRules('email', 'email', 'admin123@gmail....', Array, Array)
#7 C:\xampp\htdocs\CI\system\Controller.php(140): CodeIgniter\Validation\Validation->run()
#8 C:\xampp\htdocs\CI\app\Controllers\signup.php(26): CodeIgniter\Controller->validate(Array)
#9 C:\xampp\htdocs\CI\system\CodeIgniter.php(927): App\Controllers\signup->store()
#10 C:\xampp\htdocs\CI\system\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\signup))
#11 C:\xampp\htdocs\CI\system\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 C:\xampp\htdocs\CI\public\index.php(67): CodeIgniter\CodeIgniter->run()
#13 {main}
CRITICAL - 2022-11-11 09:23:54 --> Call to a member function getRow() on bool
in SYSTEMPATH\Validation\Rules.php on line 142.
 1 SYSTEMPATH\Validation\Validation.php(315): CodeIgniter\Validation\Rules->is_unique('admin123@gmail.com', 'email', [...], null, 'email')
 2 SYSTEMPATH\Validation\Validation.php(175): CodeIgniter\Validation\Validation->processRules('email', 'email', 'admin123@gmail.com', [...], [...])
 3 SYSTEMPATH\Controller.php(140): CodeIgniter\Validation\Validation->run()
 4 APPPATH\Controllers\signup.php(26): CodeIgniter\Controller->validate([...])
 5 SYSTEMPATH\CodeIgniter.php(927): App\Controllers\signup->store()
 6 SYSTEMPATH\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\signup))
 7 SYSTEMPATH\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
ERROR - 2022-11-11 09:38:35 --> mysqli_sql_exception: Table 'zavme.users' doesn't exist in C:\xampp\htdocs\CI\system\Database\MySQLi\Connection.php:292
Stack trace:
#0 C:\xampp\htdocs\CI\system\Database\MySQLi\Connection.php(292): mysqli->query('SELECT 1\nFROM `...', 0)
#1 C:\xampp\htdocs\CI\system\Database\BaseConnection.php(666): CodeIgniter\Database\MySQLi\Connection->execute('SELECT 1\nFROM `...')
#2 C:\xampp\htdocs\CI\system\Database\BaseConnection.php(593): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT 1\nFROM `...')
#3 C:\xampp\htdocs\CI\system\Database\BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query('SELECT 1\nFROM `...', Array, false)
#4 C:\xampp\htdocs\CI\system\Validation\Rules.php(142): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp\htdocs\CI\system\Validation\Validation.php(315): CodeIgniter\Validation\Rules->is_unique('admin13@gmail.c...', 'email', Array, NULL, 'email')
#6 C:\xampp\htdocs\CI\system\Validation\Validation.php(175): CodeIgniter\Validation\Validation->processRules('email', 'email', 'admin13@gmail.c...', Array, Array)
#7 C:\xampp\htdocs\CI\system\Controller.php(140): CodeIgniter\Validation\Validation->run()
#8 C:\xampp\htdocs\CI\app\Controllers\SignupController.php(24): CodeIgniter\Controller->validate(Array)
#9 C:\xampp\htdocs\CI\system\CodeIgniter.php(927): App\Controllers\SignupController->store()
#10 C:\xampp\htdocs\CI\system\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\SignupController))
#11 C:\xampp\htdocs\CI\system\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 C:\xampp\htdocs\CI\public\index.php(67): CodeIgniter\CodeIgniter->run()
#13 {main}
CRITICAL - 2022-11-11 09:38:35 --> Call to a member function getRow() on bool
in SYSTEMPATH\Validation\Rules.php on line 142.
 1 SYSTEMPATH\Validation\Validation.php(315): CodeIgniter\Validation\Rules->is_unique('admin13@gmail.com', 'email', [...], null, 'email')
 2 SYSTEMPATH\Validation\Validation.php(175): CodeIgniter\Validation\Validation->processRules('email', 'email', 'admin13@gmail.com', [...], [...])
 3 SYSTEMPATH\Controller.php(140): CodeIgniter\Validation\Validation->run()
 4 APPPATH\Controllers\SignupController.php(24): CodeIgniter\Controller->validate([...])
 5 SYSTEMPATH\CodeIgniter.php(927): App\Controllers\SignupController->store()
 6 SYSTEMPATH\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\SignupController))
 7 SYSTEMPATH\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
ERROR - 2022-11-11 09:45:19 --> mysqli_sql_exception: Table 'zavme.users' doesn't exist in C:\xampp\htdocs\CI\system\Database\MySQLi\Connection.php:292
Stack trace:
#0 C:\xampp\htdocs\CI\system\Database\MySQLi\Connection.php(292): mysqli->query('SELECT 1\nFROM `...', 0)
#1 C:\xampp\htdocs\CI\system\Database\BaseConnection.php(666): CodeIgniter\Database\MySQLi\Connection->execute('SELECT 1\nFROM `...')
#2 C:\xampp\htdocs\CI\system\Database\BaseConnection.php(593): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT 1\nFROM `...')
#3 C:\xampp\htdocs\CI\system\Database\BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query('SELECT 1\nFROM `...', Array, false)
#4 C:\xampp\htdocs\CI\system\Validation\Rules.php(142): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp\htdocs\CI\system\Validation\Validation.php(315): CodeIgniter\Validation\Rules->is_unique('admin13@gmail.c...', 'email', Array, NULL, 'email')
#6 C:\xampp\htdocs\CI\system\Validation\Validation.php(175): CodeIgniter\Validation\Validation->processRules('email', 'email', 'admin13@gmail.c...', Array, Array)
#7 C:\xampp\htdocs\CI\system\Controller.php(140): CodeIgniter\Validation\Validation->run()
#8 C:\xampp\htdocs\CI\app\Controllers\SignupController.php(24): CodeIgniter\Controller->validate(Array)
#9 C:\xampp\htdocs\CI\system\CodeIgniter.php(927): App\Controllers\SignupController->store()
#10 C:\xampp\htdocs\CI\system\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\SignupController))
#11 C:\xampp\htdocs\CI\system\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 C:\xampp\htdocs\CI\public\index.php(67): CodeIgniter\CodeIgniter->run()
#13 {main}
CRITICAL - 2022-11-11 09:45:19 --> Call to a member function getRow() on bool
in SYSTEMPATH\Validation\Rules.php on line 142.
 1 SYSTEMPATH\Validation\Validation.php(315): CodeIgniter\Validation\Rules->is_unique('admin13@gmail.com', 'email', [...], null, 'email')
 2 SYSTEMPATH\Validation\Validation.php(175): CodeIgniter\Validation\Validation->processRules('email', 'email', 'admin13@gmail.com', [...], [...])
 3 SYSTEMPATH\Controller.php(140): CodeIgniter\Validation\Validation->run()
 4 APPPATH\Controllers\SignupController.php(24): CodeIgniter\Controller->validate([...])
 5 SYSTEMPATH\CodeIgniter.php(927): App\Controllers\SignupController->store()
 6 SYSTEMPATH\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\SignupController))
 7 SYSTEMPATH\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
ERROR - 2022-11-11 11:34:45 --> mysqli_sql_exception: Table 'zavme.users' doesn't exist in C:\xampp\htdocs\CI\system\Database\MySQLi\Connection.php:292
Stack trace:
#0 C:\xampp\htdocs\CI\system\Database\MySQLi\Connection.php(292): mysqli->query('SELECT 1\nFROM `...', 0)
#1 C:\xampp\htdocs\CI\system\Database\BaseConnection.php(666): CodeIgniter\Database\MySQLi\Connection->execute('SELECT 1\nFROM `...')
#2 C:\xampp\htdocs\CI\system\Database\BaseConnection.php(593): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT 1\nFROM `...')
#3 C:\xampp\htdocs\CI\system\Database\BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query('SELECT 1\nFROM `...', Array, false)
#4 C:\xampp\htdocs\CI\system\Validation\Rules.php(142): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp\htdocs\CI\system\Validation\Validation.php(315): CodeIgniter\Validation\Rules->is_unique('admin123@gmail....', 'email', Array, NULL, 'email')
#6 C:\xampp\htdocs\CI\system\Validation\Validation.php(175): CodeIgniter\Validation\Validation->processRules('email', 'email', 'admin123@gmail....', Array, Array)
#7 C:\xampp\htdocs\CI\system\Controller.php(140): CodeIgniter\Validation\Validation->run()
#8 C:\xampp\htdocs\CI\app\Controllers\SignupController.php(24): CodeIgniter\Controller->validate(Array)
#9 C:\xampp\htdocs\CI\system\CodeIgniter.php(927): App\Controllers\SignupController->store()
#10 C:\xampp\htdocs\CI\system\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\SignupController))
#11 C:\xampp\htdocs\CI\system\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 C:\xampp\htdocs\CI\public\index.php(67): CodeIgniter\CodeIgniter->run()
#13 {main}
CRITICAL - 2022-11-11 11:34:45 --> Call to a member function getRow() on bool
in SYSTEMPATH\Validation\Rules.php on line 142.
 1 SYSTEMPATH\Validation\Validation.php(315): CodeIgniter\Validation\Rules->is_unique('admin123@gmail.com', 'email', [...], null, 'email')
 2 SYSTEMPATH\Validation\Validation.php(175): CodeIgniter\Validation\Validation->processRules('email', 'email', 'admin123@gmail.com', [...], [...])
 3 SYSTEMPATH\Controller.php(140): CodeIgniter\Validation\Validation->run()
 4 APPPATH\Controllers\SignupController.php(24): CodeIgniter\Controller->validate([...])
 5 SYSTEMPATH\CodeIgniter.php(927): App\Controllers\SignupController->store()
 6 SYSTEMPATH\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\SignupController))
 7 SYSTEMPATH\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
ERROR - 2022-11-11 11:48:36 --> mysqli_sql_exception: Table 'zavme.users' doesn't exist in C:\xampp\htdocs\CI\system\Database\MySQLi\Connection.php:292
Stack trace:
#0 C:\xampp\htdocs\CI\system\Database\MySQLi\Connection.php(292): mysqli->query('SELECT 1\nFROM `...', 0)
#1 C:\xampp\htdocs\CI\system\Database\BaseConnection.php(666): CodeIgniter\Database\MySQLi\Connection->execute('SELECT 1\nFROM `...')
#2 C:\xampp\htdocs\CI\system\Database\BaseConnection.php(593): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT 1\nFROM `...')
#3 C:\xampp\htdocs\CI\system\Database\BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query('SELECT 1\nFROM `...', Array, false)
#4 C:\xampp\htdocs\CI\system\Validation\Rules.php(142): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp\htdocs\CI\system\Validation\Validation.php(315): CodeIgniter\Validation\Rules->is_unique('admin123@gmail....', 'email', Array, NULL, 'email')
#6 C:\xampp\htdocs\CI\system\Validation\Validation.php(175): CodeIgniter\Validation\Validation->processRules('email', 'email', 'admin123@gmail....', Array, Array)
#7 C:\xampp\htdocs\CI\system\Controller.php(140): CodeIgniter\Validation\Validation->run()
#8 C:\xampp\htdocs\CI\app\Controllers\SignupController.php(25): CodeIgniter\Controller->validate(Array)
#9 C:\xampp\htdocs\CI\system\CodeIgniter.php(927): App\Controllers\SignupController->store()
#10 C:\xampp\htdocs\CI\system\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\SignupController))
#11 C:\xampp\htdocs\CI\system\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 C:\xampp\htdocs\CI\public\index.php(67): CodeIgniter\CodeIgniter->run()
#13 {main}
CRITICAL - 2022-11-11 11:48:36 --> Call to a member function getRow() on bool
in SYSTEMPATH\Validation\Rules.php on line 142.
 1 SYSTEMPATH\Validation\Validation.php(315): CodeIgniter\Validation\Rules->is_unique('admin123@gmail.com', 'email', [...], null, 'email')
 2 SYSTEMPATH\Validation\Validation.php(175): CodeIgniter\Validation\Validation->processRules('email', 'email', 'admin123@gmail.com', [...], [...])
 3 SYSTEMPATH\Controller.php(140): CodeIgniter\Validation\Validation->run()
 4 APPPATH\Controllers\SignupController.php(25): CodeIgniter\Controller->validate([...])
 5 SYSTEMPATH\CodeIgniter.php(927): App\Controllers\SignupController->store()
 6 SYSTEMPATH\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\SignupController))
 7 SYSTEMPATH\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
ERROR - 2022-11-11 12:15:56 --> mysqli_sql_exception: Duplicate entry 'user1@gmail.com' for key 'PRIMARY' in C:\xampp\htdocs\CI\system\Database\MySQLi\Connection.php:292
Stack trace:
#0 C:\xampp\htdocs\CI\system\Database\MySQLi\Connection.php(292): mysqli->query('INSERT INTO `lo...', 0)
#1 C:\xampp\htdocs\CI\system\Database\BaseConnection.php(666): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `lo...')
#2 C:\xampp\htdocs\CI\system\Database\BaseConnection.php(593): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `lo...')
#3 C:\xampp\htdocs\CI\system\Database\BaseBuilder.php(1916): CodeIgniter\Database\BaseConnection->query('INSERT INTO `lo...', Array, false)
#4 C:\xampp\htdocs\CI\system\Model.php(279): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\xampp\htdocs\CI\system\BaseModel.php(749): CodeIgniter\Model->doInsert(Array)
#6 C:\xampp\htdocs\CI\system\Model.php(667): CodeIgniter\BaseModel->insert(Array, false)
#7 C:\xampp\htdocs\CI\system\BaseModel.php(659): CodeIgniter\Model->insert(Array, false)
#8 C:\xampp\htdocs\CI\app\Controllers\SignupController.php(31): CodeIgniter\BaseModel->save(Array)
#9 C:\xampp\htdocs\CI\system\CodeIgniter.php(927): App\Controllers\SignupController->store()
#10 C:\xampp\htdocs\CI\system\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\SignupController))
#11 C:\xampp\htdocs\CI\system\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 C:\xampp\htdocs\CI\public\index.php(67): CodeIgniter\CodeIgniter->run()
#13 {main}
CRITICAL - 2022-11-11 12:15:56 --> Undefined constant "App\Controllers\login"
in APPPATH\Controllers\SignupController.php on line 33.
 1 SYSTEMPATH\CodeIgniter.php(927): App\Controllers\SignupController->store()
 2 SYSTEMPATH\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\SignupController))
 3 SYSTEMPATH\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 4 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
ERROR - 2022-11-11 12:16:07 --> mysqli_sql_exception: Duplicate entry 'user1@gmail.com' for key 'PRIMARY' in C:\xampp\htdocs\CI\system\Database\MySQLi\Connection.php:292
Stack trace:
#0 C:\xampp\htdocs\CI\system\Database\MySQLi\Connection.php(292): mysqli->query('INSERT INTO `lo...', 0)
#1 C:\xampp\htdocs\CI\system\Database\BaseConnection.php(666): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `lo...')
#2 C:\xampp\htdocs\CI\system\Database\BaseConnection.php(593): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `lo...')
#3 C:\xampp\htdocs\CI\system\Database\BaseBuilder.php(1916): CodeIgniter\Database\BaseConnection->query('INSERT INTO `lo...', Array, false)
#4 C:\xampp\htdocs\CI\system\Model.php(279): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\xampp\htdocs\CI\system\BaseModel.php(749): CodeIgniter\Model->doInsert(Array)
#6 C:\xampp\htdocs\CI\system\Model.php(667): CodeIgniter\BaseModel->insert(Array, false)
#7 C:\xampp\htdocs\CI\system\BaseModel.php(659): CodeIgniter\Model->insert(Array, false)
#8 C:\xampp\htdocs\CI\app\Controllers\SignupController.php(31): CodeIgniter\BaseModel->save(Array)
#9 C:\xampp\htdocs\CI\system\CodeIgniter.php(927): App\Controllers\SignupController->store()
#10 C:\xampp\htdocs\CI\system\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\SignupController))
#11 C:\xampp\htdocs\CI\system\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 C:\xampp\htdocs\CI\public\index.php(67): CodeIgniter\CodeIgniter->run()
#13 {main}
ERROR - 2022-11-11 12:16:20 --> mysqli_sql_exception: Duplicate entry 'user1@gmail.com' for key 'PRIMARY' in C:\xampp\htdocs\CI\system\Database\MySQLi\Connection.php:292
Stack trace:
#0 C:\xampp\htdocs\CI\system\Database\MySQLi\Connection.php(292): mysqli->query('INSERT INTO `lo...', 0)
#1 C:\xampp\htdocs\CI\system\Database\BaseConnection.php(666): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `lo...')
#2 C:\xampp\htdocs\CI\system\Database\BaseConnection.php(593): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `lo...')
#3 C:\xampp\htdocs\CI\system\Database\BaseBuilder.php(1916): CodeIgniter\Database\BaseConnection->query('INSERT INTO `lo...', Array, false)
#4 C:\xampp\htdocs\CI\system\Model.php(279): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\xampp\htdocs\CI\system\BaseModel.php(749): CodeIgniter\Model->doInsert(Array)
#6 C:\xampp\htdocs\CI\system\Model.php(667): CodeIgniter\BaseModel->insert(Array, false)
#7 C:\xampp\htdocs\CI\system\BaseModel.php(659): CodeIgniter\Model->insert(Array, false)
#8 C:\xampp\htdocs\CI\app\Controllers\SignupController.php(31): CodeIgniter\BaseModel->save(Array)
#9 C:\xampp\htdocs\CI\system\CodeIgniter.php(927): App\Controllers\SignupController->store()
#10 C:\xampp\htdocs\CI\system\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\SignupController))
#11 C:\xampp\htdocs\CI\system\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 C:\xampp\htdocs\CI\public\index.php(67): CodeIgniter\CodeIgniter->run()
#13 {main}
ERROR - 2022-11-11 12:25:39 --> mysqli_sql_exception: Duplicate entry 'user1@gmail.com' for key 'PRIMARY' in C:\xampp\htdocs\CI\system\Database\MySQLi\Connection.php:292
Stack trace:
#0 C:\xampp\htdocs\CI\system\Database\MySQLi\Connection.php(292): mysqli->query('INSERT INTO `lo...', 0)
#1 C:\xampp\htdocs\CI\system\Database\BaseConnection.php(666): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `lo...')
#2 C:\xampp\htdocs\CI\system\Database\BaseConnection.php(593): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `lo...')
#3 C:\xampp\htdocs\CI\system\Database\BaseBuilder.php(1916): CodeIgniter\Database\BaseConnection->query('INSERT INTO `lo...', Array, false)
#4 C:\xampp\htdocs\CI\system\Model.php(279): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\xampp\htdocs\CI\system\BaseModel.php(749): CodeIgniter\Model->doInsert(Array)
#6 C:\xampp\htdocs\CI\system\Model.php(667): CodeIgniter\BaseModel->insert(Array, false)
#7 C:\xampp\htdocs\CI\system\BaseModel.php(659): CodeIgniter\Model->insert(Array, false)
#8 C:\xampp\htdocs\CI\app\Controllers\SignupController.php(31): CodeIgniter\BaseModel->save(Array)
#9 C:\xampp\htdocs\CI\system\CodeIgniter.php(927): App\Controllers\SignupController->store()
#10 C:\xampp\htdocs\CI\system\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\SignupController))
#11 C:\xampp\htdocs\CI\system\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 C:\xampp\htdocs\CI\public\index.php(67): CodeIgniter\CodeIgniter->run()
#13 {main}
CRITICAL - 2022-11-11 12:25:40 --> Invalid file: login.php
in SYSTEMPATH\Exceptions\FrameworkException.php on line 33.
 1 SYSTEMPATH\View\View.php(201): CodeIgniter\Exceptions\FrameworkException::forInvalidFile('login.php')
 2 SYSTEMPATH\Common.php(1134): CodeIgniter\View\View->render('login', [], true)
 3 APPPATH\Controllers\SignupController.php(33): view('login')
 4 SYSTEMPATH\CodeIgniter.php(927): App\Controllers\SignupController->store()
 5 SYSTEMPATH\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\SignupController))
 6 SYSTEMPATH\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
ERROR - 2022-11-11 12:25:54 --> mysqli_sql_exception: Duplicate entry 'user1@gmail.com' for key 'PRIMARY' in C:\xampp\htdocs\CI\system\Database\MySQLi\Connection.php:292
Stack trace:
#0 C:\xampp\htdocs\CI\system\Database\MySQLi\Connection.php(292): mysqli->query('INSERT INTO `lo...', 0)
#1 C:\xampp\htdocs\CI\system\Database\BaseConnection.php(666): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `lo...')
#2 C:\xampp\htdocs\CI\system\Database\BaseConnection.php(593): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `lo...')
#3 C:\xampp\htdocs\CI\system\Database\BaseBuilder.php(1916): CodeIgniter\Database\BaseConnection->query('INSERT INTO `lo...', Array, false)
#4 C:\xampp\htdocs\CI\system\Model.php(279): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\xampp\htdocs\CI\system\BaseModel.php(749): CodeIgniter\Model->doInsert(Array)
#6 C:\xampp\htdocs\CI\system\Model.php(667): CodeIgniter\BaseModel->insert(Array, false)
#7 C:\xampp\htdocs\CI\system\BaseModel.php(659): CodeIgniter\Model->insert(Array, false)
#8 C:\xampp\htdocs\CI\app\Controllers\SignupController.php(31): CodeIgniter\BaseModel->save(Array)
#9 C:\xampp\htdocs\CI\system\CodeIgniter.php(927): App\Controllers\SignupController->store()
#10 C:\xampp\htdocs\CI\system\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\SignupController))
#11 C:\xampp\htdocs\CI\system\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 C:\xampp\htdocs\CI\public\index.php(67): CodeIgniter\CodeIgniter->run()
#13 {main}
CRITICAL - 2022-11-11 12:25:54 --> Invalid file: login.php
in SYSTEMPATH\Exceptions\FrameworkException.php on line 33.
 1 SYSTEMPATH\View\View.php(201): CodeIgniter\Exceptions\FrameworkException::forInvalidFile('login.php')
 2 SYSTEMPATH\Common.php(1134): CodeIgniter\View\View->render('login', [], true)
 3 APPPATH\Controllers\SignupController.php(33): view('login', [...])
 4 SYSTEMPATH\CodeIgniter.php(927): App\Controllers\SignupController->store()
 5 SYSTEMPATH\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\SignupController))
 6 SYSTEMPATH\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
ERROR - 2022-11-11 12:25:55 --> mysqli_sql_exception: Duplicate entry 'user1@gmail.com' for key 'PRIMARY' in C:\xampp\htdocs\CI\system\Database\MySQLi\Connection.php:292
Stack trace:
#0 C:\xampp\htdocs\CI\system\Database\MySQLi\Connection.php(292): mysqli->query('INSERT INTO `lo...', 0)
#1 C:\xampp\htdocs\CI\system\Database\BaseConnection.php(666): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `lo...')
#2 C:\xampp\htdocs\CI\system\Database\BaseConnection.php(593): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `lo...')
#3 C:\xampp\htdocs\CI\system\Database\BaseBuilder.php(1916): CodeIgniter\Database\BaseConnection->query('INSERT INTO `lo...', Array, false)
#4 C:\xampp\htdocs\CI\system\Model.php(279): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\xampp\htdocs\CI\system\BaseModel.php(749): CodeIgniter\Model->doInsert(Array)
#6 C:\xampp\htdocs\CI\system\Model.php(667): CodeIgniter\BaseModel->insert(Array, false)
#7 C:\xampp\htdocs\CI\system\BaseModel.php(659): CodeIgniter\Model->insert(Array, false)
#8 C:\xampp\htdocs\CI\app\Controllers\SignupController.php(31): CodeIgniter\BaseModel->save(Array)
#9 C:\xampp\htdocs\CI\system\CodeIgniter.php(927): App\Controllers\SignupController->store()
#10 C:\xampp\htdocs\CI\system\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\SignupController))
#11 C:\xampp\htdocs\CI\system\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 C:\xampp\htdocs\CI\public\index.php(67): CodeIgniter\CodeIgniter->run()
#13 {main}
CRITICAL - 2022-11-11 12:25:55 --> Invalid file: login.php
in SYSTEMPATH\Exceptions\FrameworkException.php on line 33.
 1 SYSTEMPATH\View\View.php(201): CodeIgniter\Exceptions\FrameworkException::forInvalidFile('login.php')
 2 SYSTEMPATH\Common.php(1134): CodeIgniter\View\View->render('login', [], true)
 3 APPPATH\Controllers\SignupController.php(33): view('login', [...])
 4 SYSTEMPATH\CodeIgniter.php(927): App\Controllers\SignupController->store()
 5 SYSTEMPATH\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\SignupController))
 6 SYSTEMPATH\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
ERROR - 2022-11-11 12:26:15 --> mysqli_sql_exception: Duplicate entry 'user1@gmail.com' for key 'PRIMARY' in C:\xampp\htdocs\CI\system\Database\MySQLi\Connection.php:292
Stack trace:
#0 C:\xampp\htdocs\CI\system\Database\MySQLi\Connection.php(292): mysqli->query('INSERT INTO `lo...', 0)
#1 C:\xampp\htdocs\CI\system\Database\BaseConnection.php(666): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `lo...')
#2 C:\xampp\htdocs\CI\system\Database\BaseConnection.php(593): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `lo...')
#3 C:\xampp\htdocs\CI\system\Database\BaseBuilder.php(1916): CodeIgniter\Database\BaseConnection->query('INSERT INTO `lo...', Array, false)
#4 C:\xampp\htdocs\CI\system\Model.php(279): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\xampp\htdocs\CI\system\BaseModel.php(749): CodeIgniter\Model->doInsert(Array)
#6 C:\xampp\htdocs\CI\system\Model.php(667): CodeIgniter\BaseModel->insert(Array, false)
#7 C:\xampp\htdocs\CI\system\BaseModel.php(659): CodeIgniter\Model->insert(Array, false)
#8 C:\xampp\htdocs\CI\app\Controllers\SignupController.php(31): CodeIgniter\BaseModel->save(Array)
#9 C:\xampp\htdocs\CI\system\CodeIgniter.php(927): App\Controllers\SignupController->store()
#10 C:\xampp\htdocs\CI\system\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\SignupController))
#11 C:\xampp\htdocs\CI\system\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 C:\xampp\htdocs\CI\public\index.php(67): CodeIgniter\CodeIgniter->run()
#13 {main}
ERROR - 2022-11-11 12:27:26 --> mysqli_sql_exception: Duplicate entry 'user1@gmail.com' for key 'PRIMARY' in C:\xampp\htdocs\CI\system\Database\MySQLi\Connection.php:292
Stack trace:
#0 C:\xampp\htdocs\CI\system\Database\MySQLi\Connection.php(292): mysqli->query('INSERT INTO `lo...', 0)
#1 C:\xampp\htdocs\CI\system\Database\BaseConnection.php(666): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `lo...')
#2 C:\xampp\htdocs\CI\system\Database\BaseConnection.php(593): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `lo...')
#3 C:\xampp\htdocs\CI\system\Database\BaseBuilder.php(1916): CodeIgniter\Database\BaseConnection->query('INSERT INTO `lo...', Array, false)
#4 C:\xampp\htdocs\CI\system\Model.php(279): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\xampp\htdocs\CI\system\BaseModel.php(749): CodeIgniter\Model->doInsert(Array)
#6 C:\xampp\htdocs\CI\system\Model.php(667): CodeIgniter\BaseModel->insert(Array, false)
#7 C:\xampp\htdocs\CI\system\BaseModel.php(659): CodeIgniter\Model->insert(Array, false)
#8 C:\xampp\htdocs\CI\app\Controllers\SignupController.php(31): CodeIgniter\BaseModel->save(Array)
#9 C:\xampp\htdocs\CI\system\CodeIgniter.php(927): App\Controllers\SignupController->store()
#10 C:\xampp\htdocs\CI\system\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\SignupController))
#11 C:\xampp\htdocs\CI\system\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 C:\xampp\htdocs\CI\public\index.php(67): CodeIgniter\CodeIgniter->run()
#13 {main}
ERROR - 2022-11-11 12:27:26 --> mysqli_sql_exception: Duplicate entry 'user1@gmail.com' for key 'PRIMARY' in C:\xampp\htdocs\CI\system\Database\MySQLi\Connection.php:292
Stack trace:
#0 C:\xampp\htdocs\CI\system\Database\MySQLi\Connection.php(292): mysqli->query('INSERT INTO `lo...', 0)
#1 C:\xampp\htdocs\CI\system\Database\BaseConnection.php(666): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `lo...')
#2 C:\xampp\htdocs\CI\system\Database\BaseConnection.php(593): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `lo...')
#3 C:\xampp\htdocs\CI\system\Database\BaseBuilder.php(1916): CodeIgniter\Database\BaseConnection->query('INSERT INTO `lo...', Array, false)
#4 C:\xampp\htdocs\CI\system\Model.php(279): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\xampp\htdocs\CI\system\BaseModel.php(749): CodeIgniter\Model->doInsert(Array)
#6 C:\xampp\htdocs\CI\system\Model.php(667): CodeIgniter\BaseModel->insert(Array, false)
#7 C:\xampp\htdocs\CI\system\BaseModel.php(659): CodeIgniter\Model->insert(Array, false)
#8 C:\xampp\htdocs\CI\app\Controllers\SignupController.php(31): CodeIgniter\BaseModel->save(Array)
#9 C:\xampp\htdocs\CI\system\CodeIgniter.php(927): App\Controllers\SignupController->store()
#10 C:\xampp\htdocs\CI\system\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\SignupController))
#11 C:\xampp\htdocs\CI\system\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 C:\xampp\htdocs\CI\public\index.php(67): CodeIgniter\CodeIgniter->run()
#13 {main}
ERROR - 2022-11-11 12:27:53 --> mysqli_sql_exception: Duplicate entry 'user1@gmail.com' for key 'PRIMARY' in C:\xampp\htdocs\CI\system\Database\MySQLi\Connection.php:292
Stack trace:
#0 C:\xampp\htdocs\CI\system\Database\MySQLi\Connection.php(292): mysqli->query('INSERT INTO `lo...', 0)
#1 C:\xampp\htdocs\CI\system\Database\BaseConnection.php(666): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `lo...')
#2 C:\xampp\htdocs\CI\system\Database\BaseConnection.php(593): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `lo...')
#3 C:\xampp\htdocs\CI\system\Database\BaseBuilder.php(1916): CodeIgniter\Database\BaseConnection->query('INSERT INTO `lo...', Array, false)
#4 C:\xampp\htdocs\CI\system\Model.php(279): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\xampp\htdocs\CI\system\BaseModel.php(749): CodeIgniter\Model->doInsert(Array)
#6 C:\xampp\htdocs\CI\system\Model.php(667): CodeIgniter\BaseModel->insert(Array, false)
#7 C:\xampp\htdocs\CI\system\BaseModel.php(659): CodeIgniter\Model->insert(Array, false)
#8 C:\xampp\htdocs\CI\app\Controllers\SignupController.php(31): CodeIgniter\BaseModel->save(Array)
#9 C:\xampp\htdocs\CI\system\CodeIgniter.php(927): App\Controllers\SignupController->store()
#10 C:\xampp\htdocs\CI\system\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\SignupController))
#11 C:\xampp\htdocs\CI\system\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 C:\xampp\htdocs\CI\public\index.php(67): CodeIgniter\CodeIgniter->run()
#13 {main}
ERROR - 2022-11-11 12:28:24 --> mysqli_sql_exception: Duplicate entry 'user1@gmail.com' for key 'PRIMARY' in C:\xampp\htdocs\CI\system\Database\MySQLi\Connection.php:292
Stack trace:
#0 C:\xampp\htdocs\CI\system\Database\MySQLi\Connection.php(292): mysqli->query('INSERT INTO `lo...', 0)
#1 C:\xampp\htdocs\CI\system\Database\BaseConnection.php(666): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `lo...')
#2 C:\xampp\htdocs\CI\system\Database\BaseConnection.php(593): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `lo...')
#3 C:\xampp\htdocs\CI\system\Database\BaseBuilder.php(1916): CodeIgniter\Database\BaseConnection->query('INSERT INTO `lo...', Array, false)
#4 C:\xampp\htdocs\CI\system\Model.php(279): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\xampp\htdocs\CI\system\BaseModel.php(749): CodeIgniter\Model->doInsert(Array)
#6 C:\xampp\htdocs\CI\system\Model.php(667): CodeIgniter\BaseModel->insert(Array, false)
#7 C:\xampp\htdocs\CI\system\BaseModel.php(659): CodeIgniter\Model->insert(Array, false)
#8 C:\xampp\htdocs\CI\app\Controllers\SignupController.php(31): CodeIgniter\BaseModel->save(Array)
#9 C:\xampp\htdocs\CI\system\CodeIgniter.php(927): App\Controllers\SignupController->store()
#10 C:\xampp\htdocs\CI\system\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\SignupController))
#11 C:\xampp\htdocs\CI\system\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 C:\xampp\htdocs\CI\public\index.php(67): CodeIgniter\CodeIgniter->run()
#13 {main}
